#!/bin/ash
# shellcheck shell=dash disable=1091
#Import formating
. formating
info "Attempting to to update"
[ "$(id -u)" -eq 0 ] || error "Unable to update, not enough permisions!!"
apk update
if [ -z "$(apk list -u)" ]; then
    info "No updates available"
    exit 0
fi
apk upgrade
stat=$?
if [ $stat != 0 ]; then
    error "Update proccess failed!!"
fi
# Check gdrive for updates
wget https://github.com/glotlabs/gdrive/releases/latest/download/gdrive_linux-x64.tar.gz -O "$MUSICBOX_TMP_DIR"
tar xzvf "$MUSICBOX_TMP_DIR"/gdrive_linux-x64.tar.gz
mv gdrive_linux-x64.tar.gz/gdrive /usr/bin/gdrive
rm -R "$MUSICBOX_TMP_DIR"/gdrive*