#!/bin/bash
# shellcheck shell=bash disable=1091
# Import libraries
source "$MUSICBOX_BIN_DIR/formatlib"
# Remove Temporary Files
rm -r "${MUSICBOX_TMP_DIR:?}/*"
# Remove Cached Files
rm -r "${MUSICBOX_CACHE_DIR:?}/*"
