FROM alpine:latest

# Create and set the work directory
RUN mkdir /build
WORKDIR /build

# Update the apk index
RUN apk update

# Install necessary build tools and dependencies
RUN apk add --no-cache alpine-sdk build-base apk-tools alpine-conf busybox fakeroot syslinux xorriso squashfs-tools sudo mtools dosfstools grub-efi

# Create a user and add them to the abuild group
RUN adduser build -G abuild

# Give administrative access to the abuild group
RUN echo "%abuild ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/abuild

# Switch to the build user
USER build

# Create signing keys
RUN sudo abuild-keygen -i -a

# Clone the git repository
RUN git clone --depth=1 https://gitlab.alpinelinux.org/alpine/aports.git


# Define the command to compile the Alpine Linux ISO using the answer file
CMD ["mkimg.musicbox.sh", "--answers", "/load/answerfile"]