#!/bin/bash
# shellcheck shell=bash disable=1091
#Import libraries
source "$MUSICBOX_BIN_DIR/formatlib"

#Add the functions
getvalue(){
    grep "^$1=" "$MUSICBOX_CFG_DIR/config" | sed -E "s/^$1=//"
}