#!/bin/bash
# shellcheck shell=bash

# Copyright The Red Cyclops © 2023
# This program is free software: you can redistribute it and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.

# Add the formating functions
info(){
    printf %b"[ $(date +%T) | $(basename "$0") ] "info: '\x1b[38;5;246m%s\e[0;0m\n' "$1"
}
warn(){
    printf %b"[ $(date +%T) | $(basename "$0") ] "warning: '\x1b[38;5;222m%s\e[0;0m\n' "$1"
}
error(){
    printf %b"[ $(date +%T) | $(basename "$0") ] "error: '\x1b[38;5;1m%s\e[0;0m\n' "$1"
}
critical(){
    printf %b"[ $(date +%T) | $(basename "$0") ] "CRITICAL_ERROR: '\x1b[48;5;9m\x1b[38;5;255m%s\e[0;0m\n' "$1"
}
