#!/bin/ash
# shellcheck shell=dash disable=1091
#Import libraries
. formatlib

# Add the functions
# Gets the File ID from google drive of a file specified with a regex
getfileid(){
    # Allow for searching inside folders
    if [ "$1" = "--parent" ]; then
        gdrive files list --parent "$2" | grep -i -E "$3" | sed -E 's/[ ].*//g'
    fi
    gdrive files list | grep -i -E "$1" | sed -E 's/[ ].*//g'
}
# Download a file or folder from google drive given a file id to a given path
downloadfile(){
    mkfifo error
    # shellcheck disable=2094
    gdrive files download "$1" --destination "$2" 2> error
    if grep -Eq 'fileNotDownloadable' error; then
        gdrive files export "$1" --format txt --destination "$2"
    fi
    rm error
}