#!/bin/bash
# shellcheck shell=bash disable=1091
#Import libraries
source "$MUSICBOX_BIN/libraries/formatlib"

logfile(){
    [ -z "$MUSICBOX_LOG_DIR" ] || warn "the logging directory isn't set" && export MUSICBOX_LOG_DIR="/var/log/musicbox"
    printf "%s/$(date +%Y-%m-%d).log"  "$MUSICBOX_LOG_DIR"
}