#!/bin/bash
# shellcheck shell=bash disable=1091

# Copyright The Red Cyclops © 2023
# This program is free software: you can redistribute it and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.

#Import libraries
source formatlib
source rootpermlib

info "Attempting to to update"
# Check if the program has root access
if ! rootcheck; then
 error "Unable to update, not enough permisions!!"
 exit 1
fi
# Update the package database
apt update
# Check if there are any packages to be upgraded
if [ -z "$(apt-get list --upgradable | sed 's/Listing\.\.\. Done//')" ]; then
    info "No updates available"
    exit 0
fi
# Upgrade packages

    if apt-get upgrade; then
        error "Update proccess failed!!"
    fi
# Update gdrive3
    # Download the latest version
    wget https://github.com/glotlabs/gdrive/releases/latest/download/gdrive_linux-x64.tar.gz -O "$MUSICBOX_TMP_DIR"
    # Unpack the tarball
    tar xzvf "$MUSICBOX_TMP_DIR"/gdrive_linux-x64.tar.gz
    # Update binary
    mv gdrive_linux-x64.tar.gz/gdrive "$MUSICBOX_BIN_DIR"/gdrive
    # Remove temporay files
    rm -R "$MUSICBOX_TMP_DIR"/gdrive*
# Update yt-dlp
    wget "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp" -O /usr/local/bin/yt-dlp
    chmod +x /usr/local/bin/yt-dlp