#!/bin/bash
# shellcheck shell=bash

# Copyright The Red Cyclops © 2023
# This program is free software: you can redistribute it and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.

# Adjust the fade smoothness
volume='-2%'
speed="0.1"
iterations=100

# Gradualy lower volume
i=0
while [ $i -lt $iterations ]; do
    sleep $speed
    # Get each sink and lower the volume
    for sink in $(pacmd list-sinks | grep 'index:' | cut -b12-)
    do
        pactl set-sink-volume "$sink" $volume
    done
    i=$i+1
done
exit 0
