#!/bin/ash
# shellcheck shell=dash
volume='-2%'
speed="0.1"

# Gradualy lower volume
i=0
while [ $i -lt 100 ]; do
    sleep $speed
    # Get each sink and lower the volume
    for sink in $(pacmd list-sinks | grep 'index:' | cut -b12-)
    do
        pactl set-sink-volume "$sink" $volume
    done
    i=$i+1
done
exit 0
