#!/bin/bash
# shellcheck shell=bash disable=1091

# Copyright The Red Cyclops © 2023
# This program is free software: you can redistribute it and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.

# Import libraries
source "$MUSICBOX_BIN_DIR/formatlib"
source "$MUSICBOX_BIN_DIR/gdrivelib"
# Download the configuration
# Check if the file exists if so download it
if downloadfile "$(getfileid 'Configuration')" "$MUSICBOX_TMP_DIR/dirty-config"; then
# Remove comments
grep -v '#.*' "$MUSICBOX_TMP_DIR/dirty-config" > "$MUSICBOX_CFG_DIR"/config
# Remove temporary file
rm "$MUSICBOX_TMP_DIR/dirty-config"
else
error "Configuration file not found!"
exit 1
fi
