#!/bin/bash
# shellcheck shell=bash disable=1091

# Copyright The Red Cyclops © 2023
# This program is free software: you can redistribute it and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.

# Import libraries
source "$MUSICBOX_BIN_DIR/formatlib"
source "$MUSICBOX_BIN_DIR/gdrivelib"
# Get the song list
downloadfile "$(getfileid "Song List")" "$MUSICBOX_CACHE_DIR"/song-list
# Check and format the list
# Get if any links are in the file if not warn that only using the extra songs
grep -Eq -- '^((?:https?:)?\/\/)?((?:www|m)\.)?((?:youtube(-nocookie)?\.com|youtu.be))(\/(?:[\w\-]+\?v=|embed\/|v\/)?)([\w\-]+)(\S+)?$' "$MUSICBOX_TMP_DIR/song-list"|| warn "No links were found!, only using songs from extra-songs folder!"
# Remove comments
grep -o '^[^#]*' file "$MUSICBOX_TMP_DIR"/song-list > "$MUSICBOX_TMP_DIR/clean-song-list"
# Susbstitue newlines with spaces
tr '\n' ' ' < /tmp/musicbox/clean-song-list > song-list
rm clean-song-list
# Download the songs
# From Youtube
yt-dlp -x --audio-format mp3 --audio-quality 0 --sponsorblock-remove all -o "$MUSICBOX_CACHE_DIR/music/%(id).%(ext)s" "$(cat song-list)"
# From the extra songs folder
downloadfile "$(getfileid "Extra Songs")" "$MUSICBOX_CACHE_DIR/extra-songs"
count=1
for i in "$MUSICBOX_CACHE_DIR/extra-songs/"*; do
mv "$i" "$MUSICBOX_CACHE_DIR/extra-song-$count.mp3"
count=$((count+1))
done
