#!/bin/bash
# shellcheck shell=bash disable=1091

# Copyright The Red Cyclops © 2023
# This program is free software: you can redistribute it and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.

# Import libraries
source formatlib
source gdrivelib

info "Attempting to download schedule"
# Download the schedule and remove comments
grep -v '#.*' <(downloadfile 'Schedule' /dev/stdout) >> "$MUSICBOX_CACHE_DIR"/schedule
# Verify the syntax
if ! grep -E -q '^(start|stop)/[0-9]{1,2}:[0-9]{1,2}/.+$' "$MUSICBOX_CACHE_DIR"/schedule; then
    error "Schedule is misformated!"
    cat "$MUSICBOX_CACHE_DIR"/schedule
fi
