#!/bin/bash
# shellcheck shell=bash disable=1091
#Import libraries
source "$MUSICBOX_BIN_DIR/formatlib"
source "$MUSICBOX_BIN_DIR/gdrivelib"
#download
downloadfile "$(getfileid 'Configuration')" "$MUSICBOX_TMP_DIR/dirty-config"
grep -v '#.*' "$MUSICBOX_TMP_DIR/dirty-config" > "$MUSICBOX_CONFIG_DIR"/config