#!/bin/bash
# shellcheck shell=bash disable=1091
# Import libraries
source "$MUSICBOX_BIN_DIR/formatlib"
source "$MUSICBOX_BIN_DIR/gdrivelib"
# Download the schedule
downloadfile "$(getfileid Schedule)" "$MUSICBOX_CACHE_DIR"/schedule
#Remove comments for check
grep -v -E '^[ ]*#.*' "$MUSICBOX_CACHE_DIR"/schedule > "$MUSICBOX_CACHE_DIR"/schedule-clean
mv "$MUSICBOX_CACHE_DIR"/schedule-clean "$MUSICBOX_CACHE_DIR"/schedule
# Verify the syntax
if grep -v -E -q '(\*||[0-9]{2}:[0-9]{2})[\r\t\f\v ]+(\*||[0-9]{2}:[0-9]{2})[\r\t\f\v ]*' "$MUSICBOX_CACHE_DIR"/schedule; then
    error "Schedule is misformated!"
fi