#!/bin/bash
# shellcheck shell=bash disable=1091

# Copyright The Red Cyclops © 2023
# This program is free software: you can redistribute it and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.

# Get the path of the instalation directory [WORKING]
    installpath="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 || echo "CRITICAL: failed to get the path to installation directory" ; pwd -P | sed 's/scripts\/setup//')"
# Import libraries [WORKING]
    source "$installpath/scripts/libraries/formatlib" && info "FormatLib imported"
# Import enviroment variables [WORKING]
    source "$installpath/.env" && info "Sourced enviroment"
        # Download and install gdrive
        # Create a temporary directory to store the download
        tmpdir=$(mktemp -d)
        # Set it so only this user can write to it
        chmod 700 "$tmpdir"
        # Download the binary
        ver=3.9.0
        wget "https://github.com/glotlabs/gdrive/releases/download/$ver/gdrive_linux-x64.tar.gz" -O "$tmpdir/gdrive-$ver.tar.gz"
        # Unpack the binary into the binaries directory
        tar xzf "$tmpdir/gdrive-$ver.tar.gz" -C "$MUSICBOX_BIN_DIR/"
        # Make the binary executable
        chmod +x "$MUSICBOX_BIN_DIR"/gdrive
        # Remove all temporary files
        rm -R "$tmpdir"
        # Download and install yt-dlp (latest)
        wget "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp" -O /usr/local/bin/yt-dlp
        chmod +x /usr/local/bin/yt-dlp

# Copy scripts to bin
    # Gets all files and sends them as arguments to copy that copies them to the binaries directory
    find "$installpath/scripts" -type f -exec cp {} "$MUSICBOX_BIN_DIR/" \; && info "Copied scripts to $MUSICBOX_BIN_DIR"
    # Make all scripts executable
    chmod -R +x "$MUSICBOX_BIN_DIR"
#Create checksums for integrity testing
sha1sum "$MUSICBOX_BIN_DIR"/* > "$MUSICBOX_CFG_DIR"/sha1sums
# Give it access to all the needed directories

info "Instalation Finished"