#!/bin/bash
# shellcheck shell=bash disable=1091

# Copyright The Red Cyclops © 2023
# This program is free software: you can redistribute it and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>. 

# Get the path of the instalation directory
installpath="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 || echo "CRITICAL: failed to get the path to installation directory" ; pwd -P | sed 's/scripts\/setup//')"
# Import libraries
source "$installpath/scripts/libraries/formatlib"
source "$installpath/scripts/libraries/rootpermlib"
# Import enviroment variables
source "$installpath/scripts/musicbox-env"
# Add them to the default enviroment
cp "$installpath/scripts/musicbox-env" /usr/lib/enviroment.d/musicbox.conf
# Install packages
apt install ffmpeg mp3gain mp3val s-nail postfix pulseaudio pulseaudio-utils vlc yt-dlp
# Download and install gdrive
# Create a temporary directory to store the download
tmpdir=$(mktemp -d)
# Set it so only this user can write to it
chmod 700 $tmpdir
ver=3.9.0
wget "https://github.com/glotlabs/gdrive/releases/download/$ver/gdrive_linux-x64.tar.gz" -O $tmpdir/gdrive-$ver.tar.gz
tar xzf /var/tmp/gdrive-$ver.tar.gz -C $MUSICBOX_BIN/
chmod +x $MUSICBOX_BIN/gdrive
rm -R $tmpdir
# Unpack the credentials to be used
echo "Getting Credentials"
unzip $installpath/creds.tar
# Enable cron
systemctl enable cron --now
# Add unprivileged user
adduser -h /opt/musicbox-unprivilieged-user-files "$MUSICBOX_USER"
mkdir "$MUSICBOX_CACHE_DIR"
chown "$MUSICBOX_USER" "$MUSICBOX_CACHE_DIR"
# Setup drive access
su "$MUSICBOX_USER" -c "gdrive account import $installpath/creds/gdrive_export-***REMOVED***.tar"
# Setup default crontabs
crontab "$installpath/cron/rootcron.txt"
su "$MUSICBOX_USER" -c "crontab \"$installpath/cron/usercron.txt\""
# Copy scripts to bin
find scripts -type f -exec cp {} $MUSICBOX_BIN \;
# Setup mail
touch /etc/postfix/sasl_password
chmod 600 