#!/bin/bash
# shellcheck shell=bash disable=1091

# Copyright The Red Cyclops © 2023
# This program is free software: you can redistribute it and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>. 

# Get the path to the script
scriptpath="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 || echo "CRITICAL: failed to get the path to the script" ; pwd -P )"
# Import libraries
. "$scriptpath/scripts/libraries/formatlib"
. "$scriptpath/scripts/libraries/rootpermlib"
# Import enviroment variables
. "$scriptpath/scripts/musicbox-env"
# Add them to the default enviroment

# Define locations
bin=/usr/local/bin
# Enable all extra repos
cat <<EOF > /etc/apk/repositories
#normal repos
https://dl-cdn.alpinelinux.org/alpine/v3.18/main
https://dl-cdn.alpinelinux.org/alpine/v3.18/community
#extra repos
@edge         https://dl-cdn.alpinelinux.org/alpine/edge/main
@edgecomunity https://dl-cdn.alpinelinux.org/alpine/edge/community
@testing      https://dl-cdn.alpinelinux.org/alpine/edge/testing
EOF
# Setup Network Time Protocol
setup-ntp
# Install packages
apk add ffmpeg mp3gain@testing mp3val@testing s-nail postfix pulseaudio pulseaudio-utils vlc yt-dlp
# Download and install gdrive
ver=3.9.0
wget "https://github.com/glotlabs/gdrive/releases/download/$ver/gdrive_linux-x64.tar.gz" -O /var/tmp/gdrive-$ver.tar.gz
tar xzf /var/tmp/gdrive-$ver.tar.gz -C $bin/
rm /var/tmp/gdrive-$ver.tar.gz
# Unpack the credentials to be used
echo "Getting Credentials"
unzip creds.tar
# Enable cron
rc-service crond start && rc-update add crond
# Add unprivileged user
adduser -h /opt/musicbox-unprivilieged-user-files "$MUSICBOX_USER"
mkdir "$MUSICBOX_CACHE_DIR"
chown "$MUSICBOX_USER" "$MUSICBOX_CACHE_DIR"
# Setup drive access
su "$MUSICBOX_USER" -c "gdrive account import creds/gdrive_export-***REMOVED***.tar"
# Setup default crontabs
crontab "$scriptpath/cron/rootcron.txt"
su "$MUSICBOX_USER" -c "crontab \"$scriptpath/cron/usercron.txt\""
# Copy scripts to bin
# Grep removes omitting dir  ectory warning as it is copied later
cp "$scriptpath/scripts/startup/musicbox-load" $bin 2>&1 | grep -v -E 'omitting directory'
cp "$scriptpath/scripts/"* "$MUSICBOX_BIN"
# Generate default slots
mkdir /usr/local/slots
slotgen 7
# Setup mail
touch /etc/postfix/sasl_password
chmod 600 