#!/bin/bash
# shellcheck shell=bash disable=1091

# Copyright The Red Cyclops © 2023
# This program is free software: you can redistribute it and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.

# Import libraries
source formatlib
# Import Enviroment variables
while IFS= read -r line; do
    export "${line?}"
done < /etc/musicbox/musicbox-env # Had to hardcode this path
# Check what user the script is running as:
echo "The user that this script is running as: ${USER}"
echo "$MUSICBOX_USER"
case $USER in
    "$MUSICBOX_USER") true;; #Do nothing
    root) su "$MUSICBOX_USER" -c "$0" ;;
    *) critical  "This script must be run by either $MUSICBOX_USER or root";; 
esac
# Start the load process
"$MUSICBOX_BIN_DIR/load" | tee /var/log/musicbox.log