#!/bin/ash
# shellcheck shell=dash disable=1091
#Import libraries
. formatlib

latest_critical_error=$(sort -z logs | grep -l 'CRITICAL:')

mail <<EOF
Subject: Critical MusicBox System Failure
The issue seems to be the following $latest_critical_error
please solve it and reply to this email with: "RELOAD" as the subject
full logs are attached
EOF