#!/bin/bash
# shellcheck shell=bash
for song in "$@"; do
 file "$song" | grep "Audio File" || warn "one of the files in extra songs wasn't a song or a song wasn't correctly downloaded!" && continue
 mp3val -f "$song"
done