#!/bin/bash
# shellcheck shell=bash disable=1091

# Copyright The Red Cyclops © 2023
# This program is free software: you can redistribute it and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
# Import libraries
source formatlib
# Loop trought all songs
for song in "$MUSICBOX_CACHE_DIR/extra-songs"/*; do
    if ! file "$song" | grep "Audio File"; then
        warn "one of the files in extra songs wasn't a song or wasn't correctly downloaded!"
        continue
    fi
    mp3val -f "$song"
    info "$(mp3info -p "%b corrupted audio frames") $song"
done