#!/bin/ash
# shellcheck shell=dash disable=1091
#Import formating
. formating
info "Attempting to to update"
[ "$(id -u)" -eq 0 ] || error "Unable to update, not enough permisions!!"
apk update
if [ -z "$(apk list -u)" ]; then
    info "No updates available"
    exit 0
fi
apk upgrade
stat=$?
if [ $stat != 0 ]; then
    error "Update proccess failed!!"
fi
