#!/bin/ash
# shellcheck shell=dash disable=1091
# Create pidfile
echo $$ > /run/musicbox.pid
# Import libraries
. "$MUSICBOX_BIN/libraries/formatlib"
. "$MUSICBOX_BIN/libraries/configlib"
# Download the necesary files
"$MUSICBOX_BIN/downloaders/down-config"   &
"$MUSICBOX_BIN/downloaders/down-schedule" &
"$MUSICBOX_BIN/downloaders/down-songs"    &
# Check if post-processing is enabled
# Wait to finish getting the configuration
wait "$(pidof get-configuration)"
if getvalue post-processing; then
    # Wait for the all the songs to be downloaded
    wait "$(pidof get-songs)"
    # Run the post-processor
    "$MUSICBOX_BIN/sound/post-processor"
fi
# Check if a critical error has happened, if so send a email about it
wait
if grep -q -- 'CRITICAL_ERROR' "$MUSICBOX_LOG_DIR/$(date +%Y-%m-%d)"; then
    alert-mail
fi
scheduler
rm /run/musicbox.pid