#!/bin/bash
# shellcheck shell=bash disable=1091

# Copyright The Red Cyclops © 2023
# This program is free software: you can redistribute it and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.

# Import libraries
source "$MUSICBOX_BIN_DIR/formatlib"
source "$MUSICBOX_BIN_DIR/configlib"

info "Attempting to load schedule"

# Get when the program should run again
reloadtime=$(getvalue reload-time)
# Separate it into Hours and Minutes
reloadhour=$(echo "$reloadtime" | cut -d':' -f1)
reloadmin=$(echo "$reloadtime" | cut -d':' -f2)
# Validate the time
if [ "$reloadhour" -gt 24 ]; then
    reloadhour=23
    reloadmin=59
    warn "Hour field on reload time was over 23 setting to 23 and minutes to 59"
fi
if [ "$reloadmin" -gt 59 ]; then
    reloadmin=59
    warn "Minute field on reload time was over 59 setting to 59"
fi

# Write start of crontab to a temporary file
info "Writting crontab"
echo "
#User Cron tab
# min    hour    day    month    weekday    command
  @reboot    $MUSICBOX_BIN_DIR/load | tee $MUSICBOX_LOG_DIR/$(date +%Y-%m-%d).log
  $reloadmin      $reloadhour       *      *        1-5        $MUSICBOX_BIN_DIR/load | tee $MUSICBOX_LOG_DIR/$(date +%Y-%m-%d)/.log"\
   > "$MUSICBOX_CACHE_DIR/newcrontab.txt"

# Set the schedule file
schedule="$MUSICBOX_CACHE_DIR/schedule"
# Check that the schedule file exists
[ -f "$schedule" ] || critical "Schedule file wasn't downloaded"
# Create functions
getmode(){
    cut -d'/' -f1 "$schedule" | "sed ${1}q:d"
}
gettime(){
    cut -d'/' -f2 "$schedule" | "sed ${1}q:d"
}
getsong(){
    song=$(cut -d'/' -f3 "$schedule" | "sed ${1}q:d")
    if [[ "$song" == "random" ]]; then
        for song in "$MUSICBOX_CACHE_DIR"/songs/*; do
            if ! grep -q "$song" playedsongs; then
                break
            fi
        done
        echo "$song"
    else
    echo "$song"
    fi
}
# Parse schedule
line=0
while [[ $line -le $(wc -l "$schedule") ]]; do
    if [[ $(getmode $line) == "start" ]]; then
        date "+%M   %H  *   *   *   cvlc --no-video $(getsong $line)" --date="$(gettime $line)" >> "$MUSICBOX_CACHE_DIR/newcrontab.txt"
    elif [[ $(getmode $line) == "stop" ]]; then
        etime="$(date '+%s' --date="$(gettime $line)")"
        songduration="$(mp3info -p "%S" "$(getsong $line)")"
        fetime=$((etime-songduration))
        date "+%M   %H  *   *   *   cvlc --no-video $(getsong $line)" --date="@$fetime" >> "$MUSICBOX_CACHE_DIR/newcrontab.txt"
    fi
done

# Schedule Cleanup
date "+%M   %H  *   *   *   $MUSICBOX_BIN_DIR/cleanup" --date="$(getvalue cleanup-time)" >> "$MUSICBOX_CACHE_DIR/newcrontab.txt"

# Add newline at the end of crontab
printf '\n' >> "$MUSICBOX_CACHE_DIR/newcrontab.txt"

# Set newcrontab.txt to be the crontab
crontab "$MUSICBOX_CACHE_DIR/newcrontab.txt"

# Remove the temporary cron file

rm "$MUSICBOX_CACHE_DIR/newcrontab.txt"