#!/bin/ash
# shellcheck shell=dash
if [ -z "$1" ]; then
    error "number of slots not supplied!"
fi
for i in $(seq 1 "$1"); do
#template for a slot
cat  << EOF > "/usr/local/slots/slot$i"
#!/bin/ash
# shellcheck shell=dash
vlc /var/cache/musicbox/song$i.mp3

EOF
done