name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg MUSICBOX_BIN_DIR=/usr/lib/musicbox --build-arg MUSICBOX_TMP_DIR=/var/tmp/musicbox --build-arg MUSICBOX_LOG_DIR=/var/log/musicbox --build-arg MUSICBOX_CFG_DIR=/etc/musicbox --build-arg MUSICBOX_CACHE_DIR=/var/cache/musicbox --build-arg MUSICBOX_USER_DIR=/var/local/musicbox --build-arg MUSICBOX_USER=musicbox --build-arg MUSICBOX_USER_GID=1002 --build-arg MUSICBOX_USER_UID=1002 --tag musicbox:$(date +%s)
